add runtime definitions for rabbitmq
michaelklishin/rabbit-hole pull request #170
Opened 2020-12-21 20:27 UTC by pathcl

Hello,

Nice library! thanks for making it open source. I tried to find a way to get whole rabbitmq configuration but couldn't find it.

Idea here is to get full config from rabbitmq runtime. Eventually this could be used along with terraform to eventually import/manage it.

2020-12-22 21:33 UTC, michaelklishin requested changes
Thank you for taking the time to contribute.

I'm afraid using interfaces for most entity collections is not something we would be interested in doing. This significantly reduces the amount of effort involved but makes it very hard to reason about the structure of responses.

You can use [Hop](https://github.com/rabbitmq/hop) as an example of a library that supports definition import and export in a more type-safe manner.

I'd understand if you decide against spending more time on this PR.

2020-12-22 21:45 UTC, pathcl commented
Hey,

Would it be ok if I replace all interfaces for specific types? I can
improve it

On Tue, 22 Dec 2020 at 22:33 Michael Klishin <notifications@github.com>
wrote:

> *@michaelklishin* requested changes on this pull request.
>
> Thank you for taking the time to contribute.
>
> I'm afraid using interfaces for most entity collections is not something
> we would be interested in doing. This significantly reduces the amount of
> effort involved but makes it very hard to reason about the structure of
> responses.
>
> You can use Hop <https://github.com/rabbitmq/hop> as an example of a
> library that supports definition import and export in a more type-safe
> manner.
>
> I'd understand if you decide against spending more time on this PR.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/michaelklishin/rabbit-hole/pull/170#pullrequestreview-557379060>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA4YEQGLSEVY3M6C64HBZPTSWEGB3ANCNFSM4VEWE6VQ>
> .
>

2020-12-24 22:35 UTC, michaelklishin commented
@pathcl sure, that's what I had in mind. Thank you. Can we please introduce a new type for global parameters? I can help get it over the finish line do it if you are not familiar with them.

2020-12-24 22:36 UTC, michaelklishin requested changes
This is definitely a step in the right direction. Let's also cover global parameters.

2020-12-26 06:34 UTC, michaelklishin commented on runtime_parameters.go
> +type RuntimeDefinitions struct {
They are called just [definitions](https://www.rabbitmq.com/definitions.html), not runtime definitions. A lot of them have nothing to do with runtime parameters and do not change at runtime (e.g. product version).

2020-12-26 06:34 UTC, michaelklishin commented on runtime_parameters.go
> +func (c *Client) ListRuntimeDefinitions() (p *RuntimeDefinitions, err error) {
This should be renamed per the comment above.

2020-12-26 07:14 UTC, merged

2020-12-26 07:15 UTC, michaelklishin commented
Finished this and merged manually. Thank you. We may want to compare the global runtime parameters serialization to that of Hop but I'm reasonably confident in this feature as is.